name: PHP unit test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-24.04]
        php-versions: ['8.0', '8.1', '8.2']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Composer install
      run: composer install

    - name: Unit tests
      run: |
        ls -al
        cd tests
        ls -al
        ../vendor/bin/phpunit --color
